export const mockData = [
  {
    ref_id: 231,
    customer: "Souptik C",
    products: "Orbea Orco M30",
    date_of_purchase: "08/08/2020",
    distribution: "Bangalore",
    status: "In Transit",
    price_rs: "800.00",
  },
  {
    ref_id: 455,
    customer: "Anangha P",
    products: "Pinarello Gan Disk",
    quantity: 2,
    date_of_purchase: "06/08/2020",
    distribution: "Hyderabad",
    status: "In Transit",
    price_rs: "900.00",
  },
  {
    ref_id: 121,
    customer: "Suranjana G",
    products: "S Works Tarmac SL7",
    quantity: 1,
    date_of_purchase: "12/08/2020",
    distribution: "Patna",
    status: "Out for Delivery",
    price_rs: "300.00",
  },
  {
    ref_id: 424,
    customer: "Nithin S",
    products: "Elite P, Shcm Dire...",
    quantity: 4,
    date_of_purchase: "07/08/2020",
    distribution: "Bangalore",
    status: "In Transit",
    price_rs: "1100.00",
  },
  {
    ref_id: 877,
    customer: "Alpit Anand",
    products: "Felt Sport E 50",
    quantity: 3,
    date_of_purchase: "12/09/2020",
    distribution: "Hyderabad",
    status: "Placed",
    price_rs: "600.00",
  },
  {
    ref_id: 235,
    customer: "Rohina M",
    products: "GR920",
    quantity: 5,
    date_of_purchase: "31/07/2020",
    distribution: "Patna",
    status: "Delivered",
    price_rs: "1250.00",
  },
  {
    ref_id: 837,
    customer: "Pratha Pratim",
    products: "HJC Atara, Abus Hy...",
    quantity: 1,
    date_of_purchase: "08/08/2020",
    distribution: "Bangalore",
    status: "Out for Delivery",
    price_rs: "850.00",
  },
  {
    ref_id: 232,
    customer: "Priya B",
    products: "New Attitude Cycle",
    quantity: 1,
    date_of_purchase: "08/08/2020",
    distribution: "Bangalore",
    status: "Pre Transit",
    price_rs: "80000.00",
  },
  {
    ref_id: 233,
    customer: "Priyansh Y",
    products: "D8 Shimano",
    quantity: 1,
    date_of_purchase: "10/08/2020",
    distribution: "Bangalore",
    status: "Pre Transit",
    price_rs: "80020.00",
  },
  {
    ref_id: 234,
    customer: "Sanjana M",
    products: "PR500 29 MTB",
    quantity: 1,
    date_of_purchase: "11/08/2020",
    distribution: "Pune",
    status: "Shipped",
    price_rs: "90000.00",
  },
  {
    ref_id: 228,
    customer: "Shivansh Mehta",
    products: "Focus Thron 6.9",
    date_of_purchase: "13/08/2020",
    distribution: "Mumbai",
    status: "In Transit",
    price_rs: "800290.00",
  },
  {
    ref_id: 236,
    customer: "Shivangi",
    products: "Caledonia Shimano",
    date_of_purchase: "14/08/2020",
    distribution: "Bhubaneshwar",
    status: "Delivered",
    price_rs: "100000.00",
  },
  {
    ref_id: 237,
    customer: "Arun A",
    products: "Orbea Orco M30",
    date_of_purchase: "14/08/2020",
    distribution: "Bangalore",
    status: "Delivered",
    price_rs: "200.00",
  },
  {
    ref_id: 238,
    customer: "Arundas K",
    products: "Caledonia Shimano",
    date_of_purchase: "08/08/2020",
    distribution: "Mumbai",
    status: "Delivered",
    price_rs: "800.00",
  },
];
